import "./globals.css";
import Chatbot from "@/components/chatbot";

export const metadata = {
  title: "crandi youtube",
  description: "Generated by crandi youtube",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <main>
          {children}
          <Chatbot />
        </main>
      </body>
    </html>
  );
}
